version: '3'

services:
  db:
    build: ./db
  nginx:
    build: ./nginx
    depends_on:
      - client
      - api
      - server-1
      - server-2
    ports:
      - '80:80'
  client:
    build: ./client
    expose:
      - '3000'
  redis:
    image: redis:alpine
    expose:
      - '6739'
  api:
    build: ./api
    depends_on:
      - redis
      - db
    expose:
      - '8080'
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_DATABASE=exco
      - MYSQL_ROOT_PASSWORD=exco
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  server-1:
    build: ./pub-sub
    depends_on:
      - db
      - redis
    expose:
      - '9000'
    environment:
      - SERVER_NAME=server-1
      - PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  server-2:
    build: ./pub-sub
    depends_on:
      - db
      - redis
    expose:
      - '9000'
    environment:
      - SERVER_NAME=server-2
      - PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
